platform:
#  - Win32
  - x64

configuration:
#  - Debug
  - Release

environment:
  BOOST_FILENAME_VERSION: 1_64_0
  BOOST_VERSION: 1.64.0

  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CMAKE_GENERATOR: Visual Studio 15 2017
      VISUAL_STUDIO_INTERNAL_VERSION: 141
      VISUAL_STUDIO_VERSION: 14.1

init:
  - ps: |
      # Determine the platform and create associate environment variables
      If ($env:Platform -Match "x86") {
        $env:ARCHITECTURE="32"
      } Else {
        $env:ARCHITECTURE="64"
        $env:CMAKE_GENERATOR_SUFFIX=" Win64"
      }
      $env:LIB_ARCHITECTURE="lib$($env:ARCHITECTURE)"
      $env:WINDOWS_ARCHITECTURE="win$($env:ARCHITECTURE)"

  - ps: $env:BOOST_ROOT="C:/Libraries/boost_$($env:BOOST_FILENAME_VERSION)"
  - ps: $env:BOOST_INCLUDEDIR="$($env:BOOST_ROOT)"
  - ps: $env:BOOST_LIBRARYDIR="$($env:BOOST_ROOT)/$($env:LIB_ARCHITECTURE)-msvc-$($env:VISUAL_STUDIO_VERSION)"
  - ps: $env:BOOST_ARCHIVE="boost_$($env:BOOST_FILENAME_VERSION)-bin-msvc-$($env:VISUAL_STUDIO_VERSION)-$($env:ARCHITECTURE).7z"

install:
  - git submodule update --init --recursive

before_build:
  - md build
  - cd build
  - ps: cmake -G "$($env:CMAKE_GENERATOR)$($env:CMAKE_GENERATOR_SUFFIX)" -DCMAKE_INSTALL_PREFIX=lib -DCMAKE_BUILD_TYPE=$env:CONFIGURATION -DBOOST_ROOT=$env:BOOST_ROOT ..

build:
  project: build/hasm.sln
  parallel: true
  verbosity: quiet

test_script:
  - ctest -C %configuration% -VV .
