os: Visual Studio 2015

platform:
  - Win32
  - x64

configuration:
  - Debug
  - Release

environment:
  BOOST_ROOT: C:\Libraries\boost_1_60_0
  BOOST_LIBRARYDIR_WIN32: C:\Libraries\boost_1_60_0\lib32-msvc-14.0
  BOOST_LIBRARYDIR_WIN64: C:\Libraries\boost_1_60_0\lib64-msvc-14.0

init:
  - cmake --version
  - msbuild /version

install:
  - git submodule update --init --recursive

before_build:
  - md build
  - cd build
  - if "%platform%"=="Win32" set GENERATOR_NAME=Visual Studio 14 2015
  - if "%platform%"=="x64"   set GENERATOR_NAME=Visual Studio 14 2015 Win64
  - if "%platform%"=="Win32" set BOOST_PATH=%BOOST_LIBRARYDIR_WIN32%
  - if "%platform%"=="x64"   set BOOST_PATH=%BOOST_LIBRARYDIR_WIN64%
  - cmake -G "%GENERATOR_NAME%" -DCMAKE_BUILD_TYPE=%configuration% -DBOOST_LIBRARYDIR="%BOOST_PATH%" -DBoost_USE_STATIC_LIBS="ON" ..

build:
  verbosity: quiet

build_script:
  - cmake --build . --config %configuration%

test_script:
  - ctest -C %configuration% -VV
