platform:
  - x64

configuration:
  - Release

environment:
  BOOST_FILENAME_VERSION: 1_64_0
  BOOST_VERSION: 1.64.0

  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      CMAKE_GENERATOR: Visual Studio 14 2015
      VISUAL_STUDIO_INTERNAL_VERSION: 140
      VISUAL_STUDIO_VERSION: 14.0

init:
  - cmake --version
  - msbuild /version

  - if [%platform%]==[x86] ( set "ARCHITECTURE=32" ) else ( set "ARCHITECTURE=64" )
  - if [%platform%]==[x64] ( set "CMAKE_GENERATOR_SUFFIX= Win64" )

  - set "GENERATOR_NAME=%CMAKE_GENERATOR%%CMAKE_GENERATOR_SUFFIX%"
  - set "LIB_ARCHITECTURE=lib%ARCHITECTURE%"
  - set "BOOST_ROOT=C:\Libraries\boost_%BOOST_FILENAME_VERSION%"
  - set "BOOST_INCLUDEDIR=%BOOST_ROOT%"
  - set "BOOST_LIBRARYDIR=%BOOST_ROOT%\%LIB_ARCHITECTURE%-msvc-%VISUAL_STUDIO_VERSION%"

  # print outs for debugging/logging
  - echo ARCHITECTURE=%ARCHITECTURE%
  - echo CMAKE_GENERATOR_SUFFIX=%CMAKE_GENERATOR_SUFFIX%
  - echo GENERATOR_NAME=%GENERATOR_NAME%
  - echo LIB_ARCHITECTURE=%LIB_ARCHITECTURE%
  - echo BOOST_ROOT=%BOOST_ROOT%
  - echo BOOST_INCLUDEDIR=%BOOST_INCLUDEDIR%
  - echo BOOST_LIBRARYDIR=%BOOST_LIBRARYDIR%

install:
  - git submodule update --init --recursive

before_build:
  - md build
  - cd build
  - cmake -G "%GENERATOR_NAME%" -DCMAKE_BUILD_TYPE=%configuration% -DBoost_USE_STATIC_LIBS=ON -DBOOST_LIBRARYDIR=%BOOST_LIBRARYDIR% ..

build:
  project: build/hasm.sln
  parallel: true
  verbosity: quiet

test_script:
  - ctest -C %configuration% -VV .
