sudo: required
dist: trusty
language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - gcc-5
            #- cmake
            #- cmake-data
      env:
        - COMPILER=g++-5
#    - compiler: clang
#      addons:
#        apt:
#         sources:
#            - ubuntu-toolchain-r-test
#          packages:
#            - cmake
#            - cmake-data
#      env: COMPILER=clang++

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libboost-all-dev

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER ..
  - make
  - cmake --version

notifications:
  email: false