language: cpp

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "QFshf+UW0T7NYVUS58x8SdrzeKPzVVa/dcOyyHYb/H6XZdppK0g/pYTBmKFmv/uyEDTDQe126WjVMLbV5XM75AMUj9EjK28RIB/0FrDHI1TxNG387Go2Xa86LlYqfaxg8UqobrWDk24pry89knqAsx63sRdnqSYV6pFbE1+pRODCm3UZeltYYd3tvBUFGqWrLzGezx8eTrR3fwAgHpp/3GYLRvMXj1kdYnNneEhARrqTVIiwzLY12JwHPhwCBUtM0X9jHsEzqSRXicgk10SLqO3z3pRpd6fk1u1PHWflhBgmPsNj8AYP/iZzb2c1tGAe/jp7NBZbIXqByAHKygMDQtC+4TaMdH2R/zSkZkcGhdq2ojsNpVAl8OiksGPVrKDANvuhnQz/wPqv+D4rfWvza3FFwjSdRLc+as43fomBe4D7HVzH9GIufyyqNw5Zae0EXoPTJjmnRw2Oa3S5PmFp6sUDCsFfLWmKuR8w8cAm1Spq0oYHZYi8tn2ig5DcBmNANXvRrJySgVDDf62oOkumqTriyK8koSBxxuPKKBsdfLqyoJf05Jy8zNO7fQp9F7ryaw/z71T2bniyf3VQVMg2Mutmc5ggPbKj4M7qmLIPmMUsbY7YMfEy3i8mKuZHz1tJzVgtLJe3YoLWU4NrmoB1Ku0HQU+t/0gQbHCGBQDfJ6c="

matrix:
  include:
    - os: linux
      sudo: required
      dist: trusty
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.8
            - gcc-4.8
          coverity_scan:
            project:
              name: "benvenutti/hasmTest"
              description: "Build submitted via Travis CI"
            notification_email: diogo.a.benvenutti@gmail.com
            build_command_prepend: "export CC=gcc-4.8 CXX=g++-4.8 && mkdir build_coverity && cd build_coverity && cmake .."
            build_command: "make -j2"
            branch_pattern: coverity_scan
      env: COMPILER=g++-4.8

    - os: linux
      sudo: required
      dist: trusty
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER=g++-5

    - os: linux
      sudo: required
      dist: trusty
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
      env: COMPILER=clang++

    - os: osx
      osx_image: xcode8
      compiler: clang

before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update -qq && sudo apt-get install -y libboost-all-dev; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update && brew install cmake; fi

script:
  - cat /home/travis/build/benvenutti/hasmTest/buildCoverity/cov-int/scm_log.txt
  - mkdir build
  - cd build
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then cmake -DCMAKE_CXX_COMPILER=$COMPILER ..; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then cmake ..; fi
  - make

notifications:
  email: false