os: Visual Studio 2015

environment:
  BOOST_ROOT: C:\Libraries\boost_1_59_0
  BOOST_LIBRARYDIR: C:\Libraries\boost_1_59_0\lib32-msvc-14.0

configuration:
  - Debug
  - Release

init:
  - cmd: cmake --version
  - cmd: msbuild /version

build_script:
  - cmd: md build
  - cmd: cd build
  - cmd: cmake -G "Visual Studio 14 2015 Win64" -DBoost_USE_STATIC_LIBS="ON" ..
  - cmd: cmake --build . --config Release
