os: Visual Studio 2015

platform:
  - Win32
  - x64

configuration:
  - Debug
  - Release

environment:
  BOOST_ROOT: C:\Libraries\boost_1_60_0
  BOOST_LIBRARYDIR_WIN32: C:\Libraries\boost_1_60_0\lib32-msvc-14.0
  BOOST_LIBRARYDIR_WIN64: C:\Libraries\boost_1_60_0\lib64-msvc-14.0

init:
  - cmd: cmake --version
  - cmd: msbuild /version

before_build:
  - cmd: md build
  - cmd: cd build
  - cmd: if "%platform%"=="Win32" set GENERATOR_NAME=Visual Studio 14 2015
  - cmd: if "%platform%"=="x64"   set GENERATOR_NAME=Visual Studio 14 2015 Win64
  - cmd: if "%platform%"=="Win32" set BOOST_PATH=%BOOST_LIBRARYDIR_WIN32%
  - cmd: if "%platform%"=="x64"   set BOOST_PATH=%BOOST_LIBRARYDIR_WIN64%
  - cmd: cmake -G "%GENERATOR_NAME%" -DCMAKE_BUILD_TYPE=%configuration% -DBOOST_LIBRARYDIR="%BOOST_PATH%" -DBoost_USE_STATIC_LIBS="ON" ..

build_script:
  - cmd: cmake --build . --config %configuration%

test_script:
  - cmd: ctest -C %configuration% -VV
