version: "{build}"

environment:
  MSVC_DEFAULT_OPTIONS: ON
  BOOST_ROOT: C:\Libraries\boost_1_59_0
  BOOST_LIBRARYDIR: C:\Libraries\boost_1_59_0\lib32-msvc-14.0

configuration:
  - Debug
  - Release

before_build:
  - mkdir build
  - cd build
  - cmake -DBoost_USE_STATIC_LIBS="ON" ..

build_script:
  - cmake --build .
