name: build

on: [push]

jobs:
  jobs_matrix:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-13, windows-2022]
        build_type: [Debug, Release]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Configure and Build
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} ..
          cmake --build . --config ${{ matrix.build_type }}
          ctest -C ${{ matrix.build_type }} -VV .
        env:
          BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}
