name: coverage

on: [push]

jobs:
  coverage:
    runs-on: ubuntu-24.04

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Create build directory
        run: mkdir build

      - name: Configure
        working-directory: ${{github.workspace}}/build
        run: cmake -DCMAKE_BUILD_TYPE=Debug -DCODE_COVERAGE=ON ..

      - name: Build
        working-directory: ${{github.workspace}}/build
        run: cmake --build . --config Debug --verbose

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C Debug -VV .
